import Navigation from "../components/navigation";
import "../styles/global.css";

export const metadata = {
  title: {
    template: "%s | Next.js",
    default: "Next.js",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation></Navigation>
        {children}
      </body>
    </html>
  );
}
